# Generated by Django 5.2 on 2025-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('medic', 'Medic'), ('freelancer', 'Freelancer'), ('corporatist', 'Corporatist'), ('student', 'Student'), ('altul', 'Altul')], max_length=20)),
                ('venit_lunar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheltuieli_lunare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economii_lunare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planuri', models.TextField(blank=True)),
            ],
        ),
    ]
