# Generated by Django 5.2 on 2025-05-03 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Numele Planului')),
                ('plan_type', models.CharField(choices=[('investitii', 'Plan de Investiții')], default='investitii', max_length=20)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Lunar'), ('quarterly', 'Trimestrial'), ('semiannual', 'Semestrial'), ('annual', 'Anual')], max_length=20)),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Investiție Inițială')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Contribuție lunară')),
                ('risk_level', models.CharField(choices=[('low', 'Scăzut'), ('medium', 'Mediu'), ('high', 'Ridicat')], max_length=10, verbose_name='Nivel de risc')),
                ('currency', models.CharField(choices=[('RON', 'RON'), ('EUR', 'EUR'), ('USD', 'USD')], default='RON', max_length=5, verbose_name='Monedă')),
                ('start_date', models.DateField(verbose_name='Data Începerii')),
                ('end_date', models.DateField(verbose_name='Data Finalizării')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
