# Generated by Django 5.2 on 2025-05-04 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_level', models.CharField(max_length=10)),
                ('years', models.PositiveIntegerField()),
                ('simulations_run', models.PositiveIntegerField(default=500)),
                ('result_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='simulator.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
