# Generated by Django 5.2 on 2025-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='monthly_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cheltuieli lunare'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Venit lunar'),
        ),
    ]
