# Generated by Django 5.2 on 2025-06-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_investmentplan_monthly_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='stock_index',
            field=models.CharField(default='^GSPC', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='payment_frequency',
            field=models.CharField(choices=[('monthly', 'Lunar'), ('quarterly', 'Trimestrial'), ('semiannual', 'Semestrial'), ('annual', 'Anual')], default='monthly', max_length=20),
        ),
    ]
