# Generated by Django 5.2 on 2025-06-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_remove_investmentplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='stock_index',
            field=models.CharField(choices=[('^GSPC', 'S&P 500'), ('^NDX', 'NASDAQ 100'), ('^DJI', 'Dow Jones'), ('^FTSE', 'FTSE 100'), ('^GDAXI', 'DAX'), ('^FCHI', 'CAC 40'), ('^N225', 'Nikkei 225'), ('^HSI', 'Hang Seng'), ('000001.SS', 'Shanghai Composite'), ('^BVSP', 'Bovespa')], default='^GSPC', max_length=20),
        ),
    ]
