# Generated by Django 5.2 on 2025-06-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_alter_investmentplan_stock_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='stock_index',
            field=models.CharField(choices=[('^GSPC', 'S&P 500 – USA, 500 companii mari'), ('^NDX', 'NASDAQ 100 – USA, companii tech'), ('^DJI', 'Dow Jones – USA, 30 companii blue chip'), ('^FTSE', 'FTSE 100 – UK, companii britanice'), ('^GDAXI', 'DAX – Germania, 40 companii mari'), ('^FCHI', 'CAC 40 – Franța'), ('^N225', 'Nikkei 225 – Japonia'), ('^HSI', 'Hang Seng – Hong Kong'), ('000001.SS', 'Shanghai Composite – China'), ('^BVSP', 'Bovespa – Brazilia')], default='^GSPC', max_length=20),
        ),
    ]
